// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext( typeof( ApplicationContext ) )]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel( ModelBuilder modelBuilder )
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation( "ProductVersion", "6.0.9" )
                .HasAnnotation( "Relational:MaxIdentifierLength", 128 );

            SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder, 1L, 1 );

            modelBuilder.Entity( "DAL.Models.CSV", b =>
                {
                    b.Property<int>( "Id" )
                        .ValueGeneratedOnAdd()
                        .HasColumnType( "int" );

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn( b.Property<int>( "Id" ), 1L, 1 );

                    b.Property<int>( "Age" )
                        .HasColumnType( "int" );

                    b.Property<string>( "PersonName" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet1" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet1Type" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet2" )
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet2Type" )
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet3" )
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet3Type" )
                        .HasColumnType( "nvarchar(max)" );

                    b.HasKey( "Id" );

                    b.ToTable( "CSV" );
                } );

            modelBuilder.Entity( "DAL.Models.Excel", b =>
                {
                    b.Property<int>( "Id" )
                        .ValueGeneratedOnAdd()
                        .HasColumnType( "int" );

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn( b.Property<int>( "Id" ), 1L, 1 );

                    b.Property<int>( "Age" )
                        .HasColumnType( "int" );

                    b.Property<string>( "PersonName" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet1" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet1Type" )
                        .IsRequired()
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet2" )
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet2Type" )
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet3" )
                        .HasColumnType( "nvarchar(max)" );

                    b.Property<string>( "Pet3Type" )
                        .HasColumnType( "nvarchar(max)" );

                    b.HasKey( "Id" );

                    b.ToTable( "Excel" );
                } );
#pragma warning restore 612, 618
        }
    }
}
